site_name: Mindustry Wiki
site_url: https://wiki.mindustry.cyou/
repo_url: https://github.com/MindustryCN/mindustrywiki
docs_dir: 'docs_out'
theme: 
  name: material
  favicon: images/favicon.png
  logo: images/favicon.png
  custom_dir: overrides
extra_css:
  - 'stylesheets/style.css'
